### ISSUE TITLE
An error occurred while removing chip suggestion.

### ISSUE THREAD

**Issue by febriantok29** [sarbagyastha/flutter_tagging#1]
Hello, I use this packages via the example folder. and I get an error like this:

```I/flutter (14131): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (14131): The following ConcurrentModificationError was thrown while handling a gesture:
I/flutter (14131): Concurrent modification during iteration: Instance(length:0) of '_GrowableList'.
I/flutter (14131): When the exception was thrown, this was the stack:
I/flutter (14131): #0      ListIterator.moveNext (dart:_internal/iterable.dart:337:7)
I/flutter (14131): #1      _FlutterTaggingState._buildSuggestions.<anonymous closure> (package:flutter_tagging/flutter_tagging.dart:424:31)
I/flutter (14131): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
I/flutter (14131): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
I/flutter (14131): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
I/flutter (14131): #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
I/flutter (14131): #6      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
I/flutter (14131): #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (14131): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:20)
I/flutter (14131): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
I/flutter (14131): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
I/flutter (14131): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (14131): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter (14131): #16     _invoke1 (dart:ui/hooks.dart:223:10)
I/flutter (14131): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
I/flutter (14131): (elided 3 frames from package dart:async)
I/flutter (14131): Handler: onTap
I/flutter (14131): Recognizer:
I/flutter (14131):   TapGestureRecognizer#32cc7(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
I/flutter (14131):   Offset(98.5, 231.5), sent tap down)
I/flutter (14131): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

my flutter doctor:
```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale id-ID)
    • Flutter version 1.2.1 at C:\Dev\flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\abay\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.1
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5124

[√] VS Code (version 1.32.3)
    • VS Code at C:\Users\abay\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • ASUS X00ID • H9AXGF00Z090RWX • android-arm64 • Android 8.1.0 (API 27)

**Comment by Johnathon332** [comment]
Hi @febriantok29 

I have fixed this issue and have created a pull request to the master, not sure when this will be reviewed and merged.

Are you still using this library?

**Comment by sarbagyastha** [comment]
Package Revived #8
